# Generated by Django 4.2.15 on 2024-09-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
