# Generated by Django 4.1 on 2024-08-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_question_choices_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='LLM_output',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
