# Generated by Django 4.2.15 on 2024-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0005_alter_question_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="LLM_output",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
